### ISSUE TITLE
Handle Predicates with Arity of /1

### ISSUE THREAD

**Issue by craigtrim** [craigtrim/prolog_antlr#14]
This works:

```prolog
    ancestor(X,Y):- 
        parent(X,Y).   		/* someone is your ancestor if there are your parent */            
```
and generates this graph:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/5699852/84826496-e0a59980-afd7-11ea-811b-405227d2ea05.png">

with this dataframe:
```text
+----+--------------------------------------+-------------+-----------------------------+--------------------------------------+
|    | UUID                                 | Type        | Text                        | Parent                               |
|----+--------------------------------------+-------------+-----------------------------+--------------------------------------|
|  0 | a941744c-b012-11ea-9f70-acde48001122 | Clause      | ancestor(X,Y):-parent(X,Y). |                                      |
|  1 | a9417816-b012-11ea-9f70-acde48001122 | Conditional | ancestor(X,Y)|parent(X,Y)   | a941744c-b012-11ea-9f70-acde48001122 |
|  2 | a9417938-b012-11ea-9f70-acde48001122 | Compound    | ancestor(X,Y)               | a9417816-b012-11ea-9f70-acde48001122 |
|  3 | a94179ba-b012-11ea-9f70-acde48001122 | Name        | ancestor                    | a9417938-b012-11ea-9f70-acde48001122 |
|  4 | a9417b68-b012-11ea-9f70-acde48001122 | Conjunction | X|Y                         | a9417938-b012-11ea-9f70-acde48001122 |
|  5 | a9417bd6-b012-11ea-9f70-acde48001122 | Variable    | X                           | a9417b68-b012-11ea-9f70-acde48001122 |
|  6 | a9417cee-b012-11ea-9f70-acde48001122 | Variable    | Y                           | a9417b68-b012-11ea-9f70-acde48001122 |
|  7 | a9417ece-b012-11ea-9f70-acde48001122 | Compound    | parent(X,Y)                 | a9417816-b012-11ea-9f70-acde48001122 |
|  8 | a9417f32-b012-11ea-9f70-acde48001122 | Name        | parent                      | a9417ece-b012-11ea-9f70-acde48001122 |
|  9 | a94180cc-b012-11ea-9f70-acde48001122 | Conjunction | X|Y                         | a9417ece-b012-11ea-9f70-acde48001122 |
| 10 | a9417bd6-b012-11ea-9f70-acde48001122 | Variable    | X                           | a94180cc-b012-11ea-9f70-acde48001122 |
| 11 | a9417cee-b012-11ea-9f70-acde48001122 | Variable    | Y                           | a94180cc-b012-11ea-9f70-acde48001122 |
+----+--------------------------------------+-------------+-----------------------------+--------------------------------------+
```

but this does not work:
```prolog
mortal(X) :- person(X).
```
generates this error:
```text
+----+--------------------------------------+-------------+-----------------------+--------------------------------------+
|    | UUID                                 | Type        | Text                  | Parent                               |
|----+--------------------------------------+-------------+-----------------------+--------------------------------------|
|  0 | 98b400ae-b012-11ea-ba15-acde48001122 | Clause      | mortal(X):-person(X). |                                      |
|  1 | 98b40414-b012-11ea-ba15-acde48001122 | Conditional | mortal(X)|person(X)   | 98b400ae-b012-11ea-ba15-acde48001122 |
|  2 | 98b404d2-b012-11ea-ba15-acde48001122 | Compound    | mortal(X)             | 98b40414-b012-11ea-ba15-acde48001122 |
|  3 | 98b40540-b012-11ea-ba15-acde48001122 | Name        | mortal                | 98b404d2-b012-11ea-ba15-acde48001122 |
|  4 | 98b40630-b012-11ea-ba15-acde48001122 | Variable    | X                     | 98b404d2-b012-11ea-ba15-acde48001122 |
|  5 | 98b407ac-b012-11ea-ba15-acde48001122 | Compound    | person(X)             | 98b40414-b012-11ea-ba15-acde48001122 |
|  6 | 98b40810-b012-11ea-ba15-acde48001122 | Name        | person                | 98b407ac-b012-11ea-ba15-acde48001122 |
|  7 | 98b40630-b012-11ea-ba15-acde48001122 | Variable    | X                     | 98b407ac-b012-11ea-ba15-acde48001122 |
+----+--------------------------------------+-------------+-----------------------+--------------------------------------+
Located Predicate: mortal
+--------+--------+--------+----------+
| UUID   | Type   | Text   | Parent   |
|--------+--------+--------+----------|
+--------+--------+--------+----------+
Traceback (most recent call last):
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/scripts/scripts/generate_graph_v2_01.py", line 28, in <module>
    main()
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/scripts/scripts/generate_graph_v2_01.py", line 24, in main
    grapher_api.graph_v2(df_ast)
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/grapher/grapher/core/bp/graphviz_api.py", line 43, in graph_v2
    gen.process(file_name="output",
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/grapher/grapher/core/svc/generate_graph_v2.py", line 100, in process
    graph, triples = triple_gen.process()
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/grapher/grapher/core/svc/generate_compound_triples.py", line 87, in process
    triples = self._extract_triples()
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/grapher/grapher/core/svc/generate_compound_triples.py", line 60, in _extract_triples
    "Triple": triple_extractor.process(row)})
  File "/Users/craig.trimibm.com/Documents/data/workspaces/personal/antlr/workspace/grapher/grapher/core/dmo/nav/compound_triple_extractor.py", line 61, in process
    raise NotImplementedError("Unexpected Condition")
NotImplementedError: Unexpected Condition
```

**Comment by craigtrim** [comment]
The parse tree visualizer works:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/5699852/84826718-38440500-afd8-11ea-91ff-ff2ef8b4f2ad.png">

**Comment by craigtrim** [comment]
Fixed

This 
```prolog
person(sam).
```

generates this:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/5699852/84839532-18b9d600-aff2-11ea-9dae-8f7928e525c8.png">


and this
```prolog
mortal(X) :- person(X).
```

generates this:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/5699852/84839561-2e2f0000-aff2-11ea-9b08-cf83bad5406f.png">
